spring:
  application:
    name: ms-theater-seat-management
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:8000/auth/realms/cinema-system

  datasource:

    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.sql

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}


server:
  port: 8082
logging:
  level:
    root: info
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

security:
  commons:
    oauth2:
      jwk-set-uri: http://${KEYCLOAK_HOST}:8000/auth/realms/cinema-system/protocol/openid-connect/certs
    cors:
      allowed-origins:
        - "*"
      allowed-headers:
        - "*"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"

springdoc:
  api-docs:
    enabled: true

  packages-to-scan: "io.cinema.empty" # Skip auto generated docs

  swagger-ui:
    path: /swagger
    url: /openapi.yaml

management:
  endpoints:
    web:
      base-path: "/"

  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://${LOKI_HOST}:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0

